name: "odoo"
description: "Odoo is an all-in-one management software that offers a range of business applications that form a complete suite of enterprise management applications targeting companies of all sizes. Odoo is an all-in-one business software including CRM, Website e-Commerce, billing, accounting, manufacturing, warehouse and project management, and inventory."
categories:
  - "erp"
type: application
version: 0.1
